### ISSUE TITLE
Scope question

### ISSUE THREAD

**Issue by philippeluickx** [apinf/docs#54]
Should the scope be limited just to dashboard? I feel that this might not be the best approach.

Typically requirements come from user needs. In this case, we have identified 2:
- API monitoring (is everything working and fast?)
- Analtyics (how is it used?)

For me the dashboard is a synthesis of these requirements. A high level overview. In order to make a good dashboard, I believe we need to therefore understand the first 2 user needs (there might be more).

**Comment by bajiat** [comment]
@philippeluickx 
> Should the scope be limited just to dashboard?

Should the scope of what be limited to dashboard?

**Comment by philippeluickx** [comment]
Wow, no idea on how this showed up here... I think this was linked to the research document that @brylie put up on the docs about Dashboard - https://github.com/apinf/docs/blob/master/docs/design/dashboard/dashboard_design_brief.md
