### ISSUE TITLE
changing tabs in APIs

### ISSUE THREAD

**Issue by wuder4** [apinf/docs#58]
You cant setup any APIs to have proxy address or delete them if you cant click tabs in the APIs page. Tabs have id's but they are in list so you cant click list with selenium.  
![list_id](https://user-images.githubusercontent.com/28555452/27330894-ebb49842-55c3-11e7-9c3f-fd3045f8a912.png)
If you add id to that link the site will break and it wont change to that tab if you click that new id.

**Comment by as33ms** [comment]
Created issue in apinf/platform repository (https://github.com/apinf/platform/issues/2672)
