### ISSUE TITLE
Can we setup continous deployment of these docs ? 

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/docs#60]
@brylie is there a historical reason for not having this repository deployed by travis (or other continuous integration software) after each commit to master?

Recently I got a [gh-pages repository](https://github.com/mauriciovieira/mauriciovieira.net) configured to [deploy any commit to master](https://github.com/mauriciovieira/mauriciovieira.net/blob/98a3d382254c88b2f86076c940e44274fcd04803/.travis.yml#L15-L21) (after some trial and errors), and would like to suggest the same kind of build for this repository.

**Comment by brylie** [comment]
Sounds like a good idea. We are currently using mkDocs to build the docs, could that also be automated?

**Comment by mauriciovieira** [comment]
[Yes](https://mauriciovieira.github.io/apinf-docs/), [it](https://github.com/mauriciovieira/apinf-docs/blob/master/.travis.yml) [can](https://travis-ci.org/mauriciovieira/apinf-docs/builds/249027031)

**Comment by mauriciovieira** [comment]
But someone with administrative privileges on the repository must [setup the keys](https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token) in order to allow travis to push to gh-pages branch.

**Comment by brylie** [comment]
I can help with the key setup. Lets discuss this further in chat.

**Comment by mauriciovieira** [comment]
I did the commits on master. It's just a matter of turning it on at https://travis-ci.org/profile/apinf and setting up the keys.

**Comment by mauriciovieira** [comment]
@brylie Can you take a look at this setup? Or I can do it, if you give me admin clearance for this repo.

**Comment by brylie** [comment]
You now have admin access.

**Comment by mauriciovieira** [comment]
@brylie. Thank you. It's done https://travis-ci.org/apinf/docs/builds/262299235
