### ISSUE TITLE
Create APInf REST API guidelines 

### ISSUE THREAD

**Issue by mauriciovieira** [apinf/docs#68]
Description at https://github.com/apinf/platform/issues/2809

# References
* [Zalando REST API guidelines](https://github.com/zalando/restful-api-guidelines)
* [Blog post about API guidelines](https://hackernoon.com/restful-api-designing-guidelines-the-best-practices-60e1d954e7c9)
- http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api 
- http://apistylebook.com/design/guidelines/
- Classic https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm

**Comment by mauriciovieira** [comment]
@matleppa @Nazarah  would  https://github.com/apinf/docs/tree/master/docs/develop be the best place to store these guidelines?

**Comment by Nazarah** [comment]
@matleppa I don't see any problem with it. :)

**Comment by mauriciovieira** [comment]
From https://github.com/apinf/platform/issues/2336#issuecomment-301167599, @frenchbread 
> 'd suggest we go simple and create something similar to RESTful SailsJS [blueprint-api](http://sailsjs.com/documentation/reference/blueprint-api) pattern. API-wise this concept has all needed features that APInf might need.
